name: null
channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - rapids=25.08
  - python=3.12
  - cuda-version[version='>=12.0,<=12.9']
  - "pytorch=2.5.1=*cuda*"
  - "pytorch-mutex=*=cuda"
  - torchvision
  - torchaudio
  - jupyterlab
  - dash
  - graphistry
  - nx-cugraph=25.08
  - "tensorflow=2.18.0=*cuda*"
  - xarray-spatial
  - dask-sql
  - code-server
  - dask-ml
  - torchinfo
  - seaborn
  - jax
  - "jaxlib=*=*cuda*"
  - dask-labextension
  - streamlit
  - streamlit-folium
  - wandb
  - gh
  - lightgbm
  - git
  - umap-learn
  - prophet
  - ignite
  - texlab
  - webcolors
  - r-languageserver
  - jedi-language-server
  - jsonschema-with-format-nongpl
  - scikit-optimize
  - catboost
 
