name: null
channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rapids=23.12
  - cuda-version=12.0
  - dask-sql
  - jupyterlab
  - dash
  - graphistry
  - xarray-spatial
  - pytorch
  - graphistry
  - dash
  - jupyterlab
  - dask-sql
  - xarray-spatial
  - pytorch
  - pytorch-lightning
  - torchvision
  - torchaudio
  - torchinfo
  - jax
  - gh
  - lightgbm
  - git
  - wandb
  - code-server
  - dask-labextension
  - hvplot
  - netcdf4
  - holoviews
  - streamlit
  - folium
  - streamlit-folium
  - seaborn
  - dask-ml
  - umap-learn
  - prophet
  - ignite
  - texlab
  - webcolors
  - r-languageserver
  - python-language-server
  - jedi-language-server
  - jsonschema-with-format-nongpl
  - pip:
    - tensorflow[and-cuda]
    - numpy==1.24